resource_registry:
  OS::TripleO::Services::Collectd: /usr/share/openstack-tripleo-heat-templates/docker/services/collectd.yaml

parameter_defaults:
#
## Collectd server configuration
   CollectdServer: 192.168.1.37
#
################
#### Other config parameters, the values shown here are the defaults
################
#
#   CollectdServerPort: 25826
#   CollectdSecurityLevel: None
#
################
#### If CollectdSecurityLevel is set to Encrypt or Sign
#### the following parameters are also needed
###############
#
#   CollectdUsername: user
#   CollectdPassword: password
#
## CollectdDefaultPlugins, These are the default plugins used by collectd
#
   CollectdDefaultPlugins:
     - disk
     - interface
     - load
     - memory
     - processes
     - tcpconns
#
## Extra plugins can be enabled by the CollectdExtraPlugins parameter:
## All the plugins availables are:
#
   CollectdExtraPlugins:
     - disk
     - df
#
## You can use ExtraConfig (or one of the related *ExtraConfig keys)
## to configure collectd.  See the documentation for puppet-collectd at
## https://github.com/voxpupuli/puppet-collectd for details.
#
   ExtraConfig:
     collectd::plugin::disk::disks:
       - "/^[vhs]d[a-f][0-9]?$/"
     collectd::plugin::df::mountpoints:
       - "/"
     collectd::plugin::df::ignoreselected: false
     collectd::plugin::cpu::valuespercentage: true
