## A Heat environment file which can be used to set up
## logging agents

resource_registry:
  OS::TripleO::Services::Fluentd: /usr/share/openstack-tripleo-heat-templates/docker/services/fluentd.yaml

parameter_defaults:
  LoggingServers:
    - host: 192.168.1.37
      port: 24224
#   - host: log1.example.com
#     port: 24224
#
## Example SSL configuration
## (note the use of port 24284 for ssl connections)
#
# LoggingServers:
#   - host: 192.168.24.11
#     port: 24284
# LoggingUsesSSL: true
# LoggingSharedKey: secret
# LoggingSSLCertificate: |
#   -----BEGIN CERTIFICATE-----
#   ...certificate data here...
#   -----END CERTIFICATE-----

